### ISSUE TITLE
An one-branch way to make the multilanguage in GH Jekyll

### ISSUE THREAD

**Issue by diev** [nicoespeon/nicoespeon.github.io#30]
Concerning your idea I found at http://www.nicoespeon.com/en/2013/04/building-a-multinlingual-jekyll-blog/

Currently I am trying a way of a RU/EN site with the following code in _layouts/default.html (RU is primary, EN is secondary) with the internal GH Jekyll only:

```html
{% if page.url == "/" or page.url == "/index.html" or page.url == "/en.html" %}
  {% assign home = true %}
{% endif %}
{% if page.url contains "/en.html" or page.url contains "-en.html" %}
  {% assign en = true %}
  <html lang="en">
{% else %}
  <html lang="ru">
{% endif %}
```

then i.e. I can format the dates in English or my native style:

```html
{% if en %}
  {{ page.date | date: "%m/%d/%Y" }}
{% else %}
  {{ page.date | date: "%d.%m.%Y" }}
{% endif %}
```

However I think there still might be a problem with the GH .paginator as you mentioned... Because I am just trying with a visitcard site, not a blog.

> I’m French and proud to be.

It's very good! I want to use GH for my native language too and looking for some ideas :)

**Comment by diev** [comment]
A good example more - https://github.com/sylvaindurand/jekyll-multilingual (EN/FR) with dual posts.

**Comment by nicoespeon** [comment]
Oh thanks @diev for the sharing and the link. Sylvain's solution seems to work well for multilingual blogs − indeed, pagination was the tricky part.

Plus, my solution worked for Jekyll v0.12 to v1.5. I guess it's out of date now − I mostly wrote on Medium lately, didn't check for Jekyll updates. 
I'm glad there are alternative solutions today, such as the one you posted 👍
